### ISSUE TITLE
The video does not load when the computer starts.

### ISSUE THREAD

**Issue by TheMystery28** [SegoCode/AutoWall#12] opened 2021-06-06 15:45 UTC
I pressed the check mark but the video does not load when the computer starts.
I've already tried to do it in several different orders before and after I press apply.
In my startup settings, AutoWall is enabled.

And sometimes the video stops.

**Comment by SegoCode** [comment] 2021-06-06 21:13
Hmmm I'm working on it, has appeared in version 1.6, you can join 1.5 while I fix it 
This is the link https://github.com/SegoCode/AutoWall/releases/tag/1.5

If you want to delete the update message, simply delete update.exe in the tools folder

I will have it solved in the next few weeks, Thxx!

**Comment by SegoCode** [comment] 2021-06-06 21:25
Also the problem is related to the location of the AutoWall folder, if you have the program located on a secondary disk it may not start with windows, try moving it to the desktop or to "Program Files" folder...

**Comment by TheMystery28** [comment] 2021-06-07 23:51
OK, thank you.

**Comment by SegoCode** [comment] 2021-06-14 07:57
> 
> 
> Also the problem is related to the location of the AutoWall folder, if you have the program located on a secondary disk it may not start with windows, try moving it to the desktop or to "Program Files" folder...

> 
> 
> OK, thank you.

Can you confirm? if the autowall path is on the desktop it starts with windows fine?

**Comment by SegoCode** [comment] 2021-06-17 18:11
Fixed in 1.7

**Closed by SegoCode** 2021-06-17 18:11 UTC
